# Generated by Django 4.0.5 on 2022-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100000)),
                ('linkedn', models.CharField(max_length=100000)),
                ('definition', models.CharField(max_length=1000000000)),
                ('bootcamp', models.CharField(max_length=50)),
            ],
        ),
    ]
